$(document).on("click", "#clear", function () {
    confirm("すべてのチェックをクリアしてよろしいですか？") && (
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(0)>div>div>div:eq(2)>input.Check0-1"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(0)>div>div>div:eq(4)>input.Check0-2"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(0)>div>div>div:eq(6)>input.Check0-3"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(0)>div>div>div:eq(8)>input.Check0-4"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(0)>div>div>div:eq(10)>input.Check0-5"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(1)>div>div>div>div:eq(0)>input.Check3-1"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(1)>div>div>div>div:eq(2)>input.Check3-2"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(1)>div>div>div>div:eq(4)>input.Check3-3"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(1)>div>div>div>div:eq(6)>input.Check3-4"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(1)>div>div>div>div:eq(8)>input.Check3-5"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(1)>div>div>div>div:eq(10)>input.Check3-6"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(1)>div>div>div>div:eq(12)>input.Check3-7"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(1)>div>div>div>div:eq(14)>input.Check3-8"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(1)>div>div>div>div:eq(16)>input.Check3-9"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(1)>div>div>div>div:eq(18)>input.Check3-10"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(2)>div>div>div>div:eq(0)>input.Check1-1"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(2)>div>div>div>div:eq(2)>input.Check1-2"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(2)>div>div>div>div:eq(3)>input.Check1-3"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(2)>div>div>div>div:eq(5)>input.Check1-4"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(0)>div>div>div:eq(0)>input.Check2-1"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(0)>div>div>div:eq(2)>input.Check2-2"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(0)>div>div>div:eq(4)>input.Check2-3"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(0)>div>div>div:eq(6)>input.Check2-4"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(0)>div>div>div:eq(8)>input.Check2-5"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(0)>div>div>div:eq(10)>input.Check2-6"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(0)>div>div>div:eq(12)>input.Check2-7"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(0)>div>div>div:eq(13)>input.Check2-8"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(0)>div>div>div:eq(15)>input.Check2-9"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(0)>div>div>div:eq(16)>input.Check2-10"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(1)>div>div>div>div:eq(0)>input.Check4-1"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(3)>div:eq(1)>div>div>div>div:eq(2)>input.Check4-2"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(0)>div>div>div:eq(1)>input.Check7-1"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(0)>div>div>div:eq(3)>input.Check7-2"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(0)>div>div>div:eq(5)>input.Check7-3"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(0)>div>div>div:eq(7)>input.Check7-4"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(0)>div>div>div:eq(9)>input.Check7-5"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(0)>div>div>div:eq(11)>input.Check7-6"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(0)>div>div>div:eq(13)>input.Check7-7"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(1)>div>div>div>div:eq(0)>input.Check5-1"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(1)>div>div>div>div:eq(2)>input.Check5-2"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(1)>div>div>div>div:eq(4)>input.Check5-3"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(1)>div>div>div>div:eq(6)>input.Check5-4"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(1)>div>div>div>div:eq(8)>input.Check5-5"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(1)>div>div>div>div:eq(10)>input.Check5-6"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(1)>div>div>div>div:eq(11)>input.Check5-7"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(1)>div>div>div>div:eq(12)>input.Check5-8"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(0)>div:eq(4)>div:eq(1)>div>div>div>div:eq(13)>input.Check5-9"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(0)>input.Check6-1"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(2)>input.Check6-2"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(4)>input.Check6-3"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(6)>input.Check6-4"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(8)>input.Check6-5"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(10)>input.Check6-6"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(12)>input.Check6-7"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(14)>input.Check6-8"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(16)>input.Check6-9"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(18)>input.Check6-10"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(20)>input.Check6-11"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(21)>input.Check6-12"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(0)>div>div>div:eq(23)>input.Check6-13"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(1)>div>div>div>div:eq(0)>input.Check8-1"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(1)>div>div>div>div:eq(2)>input.Check8-2"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(1)>div>div>div>div:eq(4)>input.Check8-3"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(1)>div>div>div>div:eq(7)>input.Check8-4"),
        localStorage.removeItem ("garlic:teito.link/task/>form>div>div:eq(1)>div:eq(1)>div>div>div>div:eq(11)>input.Check8-5"),
        location.reload()
    );
}

)